services:
  bot:
    env_file: ".env.staging"
    image: ghcr.io/viet-aus-it/discord-bot:staging
    container_name: discord_bot_staging

  db:
    env_file: ".env.staging"
    container_name: discord_bot_db_staging

  db-migrate:
    env_file: ".env.staging"
    container_name: discord_bot_db_migrate_staging
