name: Build and deploy Docker Image

on:
  push:
    branches:
      - staging
      - production
      - deploy-pipeline

jobs:
  get-deploy-stage:
    name: Get Deploy Stage
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ steps.extract_deploy_stage.outputs.stage }}

    steps:
      - name: Extract branch name
        id: extract_deploy_stage
        shell: bash
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "::set-output name=stage::${BRANCH_NAME}"

  build-discord-bot:
    name: Build Discord Bot Docker Image
    runs-on: ubuntu-latest
    needs: get-deploy-stage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/viet-aus-it/discord-bot
          tags: |
            type=ref,event=branch
            type=sha

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push docker image
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          target: production
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta.outputs.tags }}
